# Generated by Django 4.0.6 on 2022-09-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(upload_to='media/categories/'),
        ),
    ]
