export const GET_PORTFOLIO_SUCCESS = 'GET_PORTFOLIO_SUCCESS'
export const GET_PORTFOLIO_FAIL = 'GET_PORTFOLIO_FAIL'

export const GET_PORTFOLIO_LIST_SUCCESS = 'GET_PORTFOLIO_LIST_SUCCESS'
export const GET_PORTFOLIO_LIST_FAIL = 'GET_PORTFOLIO_LIST_FAIL'

export const GET_PORTFOLIO_LIST_CATEGORIES_SUCCESS = 'GET_PORTFOLIO_LIST_CATEGORIES_SUCCESS'
export const GET_PORTFOLIO_LIST_CATEGORIES_FAIL = 'GET_PORTFOLIO_LIST_CATEGORIES_FAIL'

export const GET_SEARCH_PORTFOLIO_SUCCESS = 'GET_SEARCH_PORTFOLIO_SUCCESS'
export const GET_SEARCH_PORTFOLIO_FAIL = 'GET_SEARCH_PORTFOLIO_FAIL'

export const GET_VISIT_SUCCESS = 'GET_VISIT_SUCCESS'
export const GET_VISIT_FAIL = 'GETVISIT_FAIL'
