# Generated by Django 3.2.16 on 2023-01-24 02:30

import apps.portfolio.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import froala_editor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_alter_category_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=255, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.portfolio.models.portfolio_thumbnail_directory)),
                ('description', models.TextField(max_length=255)),
                ('content', froala_editor.fields.FroalaField(blank=True, null=True)),
                ('time_read', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(blank=True, default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category.category')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfoliopost_view_count', to='portfolio.post')),
            ],
        ),
    ]
